In [1]:
import numpy as np

# Initiliaze the Data
X = np.zeros((8, 8))
for i in range(8):
    X[i, i] = 1
print(X)
Y = np.array(X)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [2]:
# Initialize Network
def initializeNetworkWeights(scale=0.01):
    W = [np.random.random((3, 8)), np.random.random((8, 3))]
    W = [(x - np.ones(x.shape) * 0.5) * scale for x in W]
    b = [np.random.random(3), np.random.random(8)]
    b = [(x - np.ones(x.shape) * 0.5) * scale for x in b]
    return W, b


W, b = initializeNetworkWeights()

In [3]:
# Define Forward

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def sigmoidPrime(x):
    return sigmoid(x) * (1 - sigmoid(x))


def mean_half_sum_squared(X, Y):
    return np.linalg.norm(X - Y) ** 2 / 2


def forward(X, W, b):
    a = X
    z_list = []
    for w, b in zip(W, b):
        z = np.matmul(w, a.T).T + b
        z_list.append(z)
        a = sigmoid(z)
    return a, z_list

In [4]:
# Getting Deltas
def getDeltas(z_list, Y, W):
    delta_list = []
    for i in reversed(range(len(z_list))):
        if i == len(z_list) - 1:
            z = z_list[i]
            a = sigmoid(z)
            delta = -(Y - a) * sigmoidPrime(z)
            delta_list.append(delta)
        else:
            z = z_list[i]
            delta = np.matmul(W[i], delta_list[len(delta_list) - 1].T).T * sigmoidPrime(z)
            delta_list.append(delta)
    return delta_list

# a, z_list = forward(X, W, b)
# delta_list=getDeltas(z_list, Y, W)
# print(delta_list)

In [5]:
#Backpropagate
def backprop(X, Y, W, b, learning_rate=0.03, weightDecay=0.01):
    a, zlist = forward(X, W, b)
    delta_list = getDeltas(zlist, Y, W)
    # Dont average here!!
    # delta_list = [np.average(x, axis=0) for x in delta_list]
    delta_list = list(reversed(delta_list))
    delta_list = [x.reshape(x.shape[0], x.shape[1], 1) for x in delta_list]
    a_list = [sigmoid(x) for x in zlist]
    a_list.insert(0, np.array(X))
    a_list = [x.reshape(x.shape[0], 1, x.shape[1]) for x in a_list]
    for i in range(len(delta_list)):
        # derivativeW = (W[i].T * delta_list[i].T).T
        derivativeW = sigmoid(a_list[i]) * delta_list[i]
        derivativeW = np.average(derivativeW, axis=0)
        # derivativeW = delta_list[i] * np.average(sigmoid(zlist[i]), axis=0).reshape(1, -1)
        # Average here!!
        W[i] = W[i] - learning_rate * derivativeW - W[i] * (weightDecay / len(X))
        b[i] = b[i] - learning_rate * np.average(delta_list[i], axis=0)
    return W, b


W, b = backprop(X, Y, W, b)

In [6]:
# Batch Gradient Descent
def batch_GD(X, Y, epoch=20000, learning_rate=0.003, weightDecay=0.01, scale=0.1):
    W, b = initializeNetworkWeights(scale)
    print(W)
    print(b)
    a, zlist = forward(X, W, b)
    print(a)
    for i in range(epoch):
        W, b = backprop(np.copy(X), Y, W, b, learning_rate, weightDecay)
        a, z_list = forward(X, W, b)
        # print(a)
        print(mean_half_sum_squared(a, Y))


batch_GD(X, Y)

[array([[-0.02884967,  0.01626814, -0.02866257, -0.03851662, -0.01578516,
        -0.00765596, -0.0130856 ,  0.01842446],
       [ 0.0173523 ,  0.01951856, -0.03806245,  0.00246673, -0.04376163,
        -0.0437161 , -0.02015557,  0.00042974],
       [-0.02351271,  0.04180304, -0.02278485, -0.00900299, -0.02791579,
         0.01286381,  0.00340044, -0.01086318]]), array([[-0.04096448, -0.04727452,  0.04292843],
       [-0.04654258,  0.035243  ,  0.01924935],
       [-0.0274557 , -0.04268283,  0.02597722],
       [-0.03051851, -0.02265094, -0.01780529],
       [ 0.03243378, -0.04837805,  0.00586708],
       [ 0.03840082, -0.03773514,  0.01554658],
       [-0.04718543,  0.00073741, -0.01037003],
       [ 0.00765437,  0.01153749, -0.0125006 ]])]
[array([-0.02598892,  0.0341803 , -0.04056249]), array([-0.00098126, -0.03966472, -0.02267543,  0.00054327,  0.01187115,
       -0.01726519, -0.02078182,  0.01472969])]
[[0.49390745 0.49127433 0.48866556 0.49136775 0.50141773 0.49739493
  0.4879102

ValueError: operands could not be broadcast together with shapes (8,3) (3,3) 